### ISSUE TITLE
Let `XOR` take multiple arguments?

### ISSUE THREAD

**Issue by christianalares** [maninak/ts-xor#22]
There is a nice example of how to use this with more than two types:
```typescript
// example1.ts

import type { XOR } from https://github.com/maninak/ts-xor

interface A {
  a: string
}

interface B {
  b: string
}

interface C {
  c: string
}

let test: XOR<A, XOR<B, C>>

test = { a: '' }         // OK
test = { b: '' }         // OK
test = { c: '' }         // OK
test = { a: '', c: '' }  // rejected
test = {}                // rejected
```

Is there a possibility to make the helper more dynamic so you can pass more than two arguments to this helper such as:
```typescript
type A = { a: string }
type B = { a: string }
type C = { a: string }
type D = { a: string }

let test: XOR<A, B, C, D>

test = { a: '' } // OK
test = { b: '' } // OK
test = { c: '' } // OK
test = { d: '' } // OK
test = { a: '', b: '' } // Rejected
test = {} // Rejected
```

I'm not a TS expert but isn't there away to spread types using the spread syntax? (`...`)

**Comment by maninak** [comment]
Hey Christian, thanks for coming over and sharing your thoughts!

I've looked into this in the past and even though I'd get the syntax to work in some cases, there would be regressions in others.

I'm a bit tight on time, but I'll look into it when possible. I'll leave the issue open regardless, in case someone can solve this puzzle and PR it in the meantime :))

**Comment by inoyakaigor** [comment]
As workaround I can propose to you these solution https://github.com/Microsoft/TypeScript/issues/14094#issuecomment-723571692

**Comment by maninak** [comment]
> As workaround I can propose to you these solution [microsoft/TypeScript#14094 (comment)](https://github.com/microsoft/TypeScript/issues/14094#issuecomment-723571692)

That's interesting (I haven't actually tested that it works as expected without regressions). Preferably, though, the feature would not be a breaking change (nor a new type would be added). 

Something like [this](https://github.com/microsoft/TypeScript/issues/14094#issuecomment-1617939552) would expand the current `XOR` type to just accept more than two arguments (like Christian proposed in the issue description).

**Comment by inoyakaigor** [comment]
_Just to clarify: under the word "you" I meant @christianalares_ 

About AllXOR. I used it in a few projects since 2020 and it works as expected but VSCode tooltips look ugly as F. 
![image](https://github.com/maninak/ts-xor/assets/1235286/f11eae15-e3c0-48a0-8bca-cba81d38d2ab)
